language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn export
deploy:
  provider: surge
  project: ./dist/
  cleanup: false
  domain: jackal.surge.sh
  on:
      branch: main